### ISSUE TITLE
我用的显卡是 华硕（ASUS）TUF3-RX5700XT-O8G-GAMING OC 1650-1870MHz

### ISSUE THREAD

**Issue by SSStq1314** [wuyexiong/asus-z390i-hackintosh-opencore#1]
请问我除了显卡不一样，使用的是华硕的 华硕（ASUS）TUF3-RX5700XT-O8G-GAMING OC 1650-1870MHz，需要做什么调整嘛，
还有就是您的那个安装配置参考文档打不开了，

**Comment by wuyexiong** [comment]
> 请问我除了显卡不一样，使用的是华硕的 华硕（ASUS）TUF3-RX5700XT-O8G-GAMING OC 1650-1870MHz，需要做什么调整嘛，
> 还有就是您的那个安装配置参考文档打不开了，

1. 应该不用调整
2. 我回头有空更新吧，搜一下 opencore官方文档就行了
